services:
  app:
    build:
      context: ./.docker/php  # Dockerfile의 실제 경로를 명확히 지정
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - ./myProject/:/var/www/html  # 로컬 프로젝트 디렉토리와 컨테이너의 /var/www/html을 마운트
    networks:
      - laravel_network
    depends_on:
      - mysql

  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    volumes:
      - ./:/var/www/html  # 동일하게 로컬 프로젝트 디렉토리와 Nginx에서 마운트
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "9090:80"
    networks:
      - laravel_network
    depends_on:
      - app

  mysql:
    image: mysql:5.7  # MySQL 5.7 버전 사용
    container_name: laravel_mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./.docker/mysql/data:/var/lib/mysql
      - ./.docker/mysql/my.cnf:/etc/mysql/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge